server:
  port: 8080
  
spring:
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
      
bigupload:
  enabled: true
  upload-path: ./uploads
  temp-path: ./uploads/temp
  base-url: http://localhost:8080
  max-file-size: 0  # 0表示不限制
  chunk-size: 2097152  # 2MB
  concurrent: 3
  api-prefix: /api/upload
  enable-file-server: true
  file-server-path: /files

logging:
  level:
    com.bigupload: INFO
    org.springframework.web.multipart: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n" 